fejler ved anden instantiering af UsersController.
System.InvalidOperationException: 'The instance of entity type 'User' cannot be tracked because another instance with the same key value for {'UserID'} is already being tracked.